name: maala_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:   
  google_nav_bar:
  image_picker: 
  path_provider: 
  path:
  permission_handler:
  audioplayers:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  rename:
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/

flutter_launcher_icons:
  image_path: "assets/images/icon_image.jpg"
  android: true
  ios: true